update object acl
Sage-Bionetworks/s3-synapse-sync pull request #15
Opened 2020-09-08 17:46 UTC by clarisse-lau

- Update bucket policy to enforce granting the bucket owner full control
- Remove Synapse arn from deny statement
- Grant Synapse read access in lambda

2020-09-08 18:24 UTC, marcomarasca requested changes
LGTM, just added one comment.

2020-09-08 18:24 UTC, marcomarasca commented on s3_synapse_sync/lambda_function.py
> +    boto3.resource('s3').ObjectAcl(bucket, key).put(GrantRead='id=d9df08ac799f2859d42a588b415111314cf66d0ffd072195f33b921db966b440')
We might want to move this call in the conditional block below (line 58). This seems to unconditionally perform a request for updating the ACL of the object, maybe we could make the call only if the file is not linked to synapse?

2020-09-08 18:34 UTC, clarisse-lau commented on s3_synapse_sync/lambda_function.py
> +    boto3.resource('s3').ObjectAcl(bucket, key).put(GrantRead='id=d9df08ac799f2859d42a588b415111314cf66d0ffd072195f33b921db966b440')
Thanks @marcomarasca. Makes sense, moved to the block indicated

2020-09-08 18:44 UTC, marcomarasca approved these changes

2020-09-08 19:11 UTC, zaro0508 requested changes

2020-09-08 19:11 UTC, zaro0508 commented on s3-synapse-sync-bucket.j2
> +                s3:x-amz-acl: bucket-owner-full-control
if we don't need `SynapseCanonicalId` and `S3CanonicalUserId` then we should remove it from the list of parameters.

2020-09-08 19:11 UTC, zaro0508 commented on s3_synapse_sync/lambda_function.py
> +        boto3.resource('s3').ObjectAcl(bucket, key).put(GrantRead='id=d9df08ac799f2859d42a588b415111314cf66d0ffd072195f33b921db966b440')
if you think there's a chance this magic number would change then you should pass it in as an environment variable

2020-09-08 19:54 UTC, clarisse-lau commented on s3-synapse-sync-bucket.j2
> +                - !Ref S3UserARNs
Thanks, fixed.

2020-09-08 19:55 UTC, clarisse-lau commented on s3-synapse-sync-bucket.j2
> +                s3:x-amz-acl: bucket-owner-full-control
Removed

2020-09-08 19:55 UTC, clarisse-lau commented on s3_synapse_sync/lambda_function.py
> +        boto3.resource('s3').ObjectAcl(bucket, key).put(GrantRead='id=d9df08ac799f2859d42a588b415111314cf66d0ffd072195f33b921db966b440')
Fixed

2020-09-08 20:42 UTC, zaro0508 requested changes

2020-09-08 20:42 UTC, zaro0508 commented on README.md
> +SynapseCanonicalId: d9df08ac799f2859d42a588b415111314cf66d0ffd072195f33b921db966b440
this doesn't seem like a bucket variable, instead it's a global variable specific to the lambda.  How about we pass in a separate `SYNAPSE_CANONICAL_ID` env var here https://github.com/Sage-Bionetworks/s3-synapse-sync/blob/master/template.yaml#L60 ?

2020-09-08 20:42 UTC, zaro0508 commented on README.md
> +SynapseCanonicalId: d9df08ac799f2859d42a588b415111314cf66d0ffd072195f33b921db966b440
also please update corresponding docs

2020-09-08 20:42 UTC, zaro0508 commented on s3-synapse-sync-bucket.j2
> -  SynapseCanonicalId:
please update corresponding docs

2020-09-08 20:53 UTC, zaro0508 commented
we cannot merge this change until we update the corresponding deployment side files (scicomp-provisioner repo) otherwise the deployment side will fail. Please push PRs with updates to these files as necessary..
* https://github.com/Sage-Bionetworks/scicomp-provisioner/blob/master/config/prod/s3-synapse-sync.yaml
* https://github.com/Sage-Bionetworks/scicomp-provisioner/blob/master/config/prod/htan-dcc-bucket-a.yaml
* https://github.com/Sage-Bionetworks/scicomp-provisioner/blob/master/config/prod/htan-dcc-center-a.yaml
* https://github.com/Sage-Bionetworks/scicomp-provisioner/blob/master/data/s3-synapse-sync-bucket-vars.yaml

2020-09-08 22:31 UTC, clarisse-lau commented on README.md
> +SynapseCanonicalId: d9df08ac799f2859d42a588b415111314cf66d0ffd072195f33b921db966b440
Changed to global env var

2020-09-08 22:33 UTC, clarisse-lau commented
@zaro0508 update as in first remove the existing lambda and buckets?

> we cannot merge this change until we update the corresponding deployment side files (scicomp-provisioner repo) otherwise the deployment side will fail. Please push PRs with updates to these files as necessary..
> 
> * https://github.com/Sage-Bionetworks/scicomp-provisioner/blob/master/config/prod/s3-synapse-sync.yaml
> * https://github.com/Sage-Bionetworks/scicomp-provisioner/blob/master/config/prod/htan-dcc-bucket-a.yaml
> * https://github.com/Sage-Bionetworks/scicomp-provisioner/blob/master/config/prod/htan-dcc-center-a.yaml
> * https://github.com/Sage-Bionetworks/scicomp-provisioner/blob/master/data/s3-synapse-sync-bucket-vars.yaml

2020-09-08 22:48 UTC, zaro0508 commented
> @zaro0508 update as in first remove the existing lambda and buckets?

These changes do not require deleting and re-creating of buckets.  If you want to delete something, like `htan-dcc-bucket-a.yaml` then push a PR to delete.  If you want to keep it then push a PR with the needed updates.

2020-09-09 14:52 UTC, zaro0508 approved these changes

2020-09-09 14:59 UTC, merged