exclude folders from sync
Sage-Bionetworks/s3-synapse-sync pull request #16
Opened 2020-09-14 05:16 UTC by clarisse-lau

- update lambda to exclude numeric 'synapse user id' folders from sync, rather than require folders be specified by center
  - handle folder deletion

2020-09-14 16:32 UTC, zaro0508 requested changes
There is no description in the commit message nor the docs on why you are making this change.  Could you please provide some context?

2020-09-14 16:59 UTC, clarisse-lau commented
Including the environment variable `foldersToSync` was originally added as a workaround to avoid syncing the ‘Synapse user ID’ folders (those with the 7-digit format e.g. ‘3413795’) to Synapse. When filehandles are added to Synapse, some metadata(I believe?)/auxiliary files are created by Synapse, which are then stored in the bucket under this new folder. These files will then trigger the lambda, and without some restriction, filehandles will be created for those files and start a loop. 

A member of the DCC did a test run of the data ingress process last week and expressed that it will be inconvenient to ask centers to pre-plan which top-level folders they will be using, and to have them inform us of these folders/any subsequent changes. We are thinking of using this somewhat hacky solution and instead of specifying which folders to sync, we will exclude those ’Synapse folders’ by only syncing folders that do not begin with a number (and instruct centers to not use such folders). This will hopefully allow centers more flexibility to add/change folders as they need.

2020-09-15 03:45 UTC, zaro0508 approved these changes

2020-09-15 03:57 UTC, zaro0508 commented on README.md
>    BucketVariables: !file_contents "data/s3-synapse-sync-bucket-vars.yaml"
Now that the bucket variables are pretty simple you should consider passing it in directly instead of using a data file.  You would do it like this..
```
BucketVariables: >-
   '{
      "htan-dcc-bucket-a":{"SynapseProjectId":"syn11111"},
      "htan-dcc-bucket-b":{"SynapseProjectId":"syn22222"}
   }'
```

2020-09-15 04:37 UTC, clarisse-lau commented on README.md
>    BucketVariables: !file_contents "data/s3-synapse-sync-bucket-vars.yaml"
Updated

2020-09-15 16:42 UTC, zaro0508 approved these changes

2020-09-15 17:31 UTC, merged