add policy and variable to deny delete obj to specific ARNs
Sage-Bionetworks/s3-synapse-sync pull request #23
Opened 2020-12-09 22:26 UTC by xdoan

2020-12-09 23:06 UTC, zaro0508 commented on s3-synapse-sync-bucket.j2
> +            Principal: {
need to remove thee `{`

2020-12-09 23:06 UTC, zaro0508 commented on s3-synapse-sync-bucket.j2
> +  DenyDeleteARNs:
i think this may not work in cases where you don't set a value for this.  Is there a use case where you don't set this?

2020-12-09 23:23 UTC, xdoan commented on s3-synapse-sync-bucket.j2
> +  DenyDeleteARNs:
There would always be at least one value at the beginning (Dave's DSA which just needs read access for his app)

2020-12-09 23:27 UTC, zaro0508 approved these changes

2020-12-09 23:27 UTC, zaro0508 commented on s3-synapse-sync-bucket.j2
> +  DenyDeleteARNs:
OK.  this will work in that case.  We may want to make it handle cases where nothing is pass in for this as well but that can be done in a follow on PR.

2020-12-09 23:27 UTC, xdoan commented on s3-synapse-sync-bucket.j2
> +  DenyDeleteARNs:
is there a way to make this optional though? This might be useful.

2020-12-09 23:32 UTC, xdoan commented on s3-synapse-sync-bucket.j2
> +  DenyDeleteARNs:
saw your comment that we can handle passing in nothing in another PR!

2020-12-09 23:42 UTC, clarisse-lau approved these changes

2020-12-10 17:14 UTC, zaro0508 requested changes

2020-12-10 17:14 UTC, zaro0508 commented on s3-synapse-sync-bucket.j2
> +            Effect: Deny,
sorry didn't catch this before but you need to remove the trailing commas.

2020-12-10 17:14 UTC, zaro0508 commented on s3-synapse-sync-bucket.j2
> +              - s3:DeleteObjectVersionTagging
how about just one `- s3:*Delete*` instead?

2020-12-10 18:37 UTC, xdoan commented on s3-synapse-sync-bucket.j2
> +            Effect: Deny,
good catch!

2020-12-10 18:37 UTC, xdoan commented on s3-synapse-sync-bucket.j2
> +              - s3:DeleteObjectVersionTagging
have updated now!

2020-12-11 19:13 UTC, zaro0508 approved these changes

2020-12-11 20:23 UTC, merged