grant DSA object read access
Sage-Bionetworks/s3-synapse-sync pull request #25
Opened 2021-02-23 02:17 UTC by clarisse-lau

Update lambda to set the object ACL, granting the Digital Slide Archive AWS account (in addition to Synapse) read access

2021-02-23 23:18 UTC, zaro0508 requested changes

2021-02-23 23:18 UTC, zaro0508 commented on template.yaml
> +          OBJECT_READ_ACCOUNTS: !Ref ObjectReadAccounts
this is a breaking change because dependent templates that provision buckets are using SYNAPSE_CANONICAL_ID.  You can do one of the following:

* version before change, basically just tag the current lambda repo, pin the dependent templates (in scicomp) to use the current version and then bump the lambda version.  make your changes then pin the dependent templates to the new version.  

OR

* keep `SYNAPSE_CANONICAL_ID` and add the new `OBJECT_READ_ACCOUNTS` VAR.  Get it working with existing buckets then remove the  existing `SYNAPSE_CANONICAL_ID` VAR.

2021-02-24 02:47 UTC, clarisse-lau commented on template.yaml
> +          OBJECT_READ_ACCOUNTS: !Ref ObjectReadAccounts
ah ok thanks @zaro0508, trying the second option

2021-02-25 20:07 UTC, zaro0508 requested changes

2021-02-25 20:07 UTC, zaro0508 commented on template.yaml
> +    Default: "id=d9df08ac799f2859d42a588b415111314cf66d0ffd072195f33b921db966b440,emailaddress=dagutman@gmail.com"
does this mean that dagutman has object read access on every bucket?  is that intentional?

2021-02-25 20:07 UTC, zaro0508 commented on template.yaml
> +  ObjectReadAccounts:
i think it would be good to add this to the documentation, let users know the default as well.

2021-02-25 20:37 UTC, clarisse-lau commented on template.yaml
> +    Default: "id=d9df08ac799f2859d42a588b415111314cf66d0ffd072195f33b921db966b440,emailaddress=dagutman@gmail.com"
yes, the DSA needs read access to objects in the HTAN buckets

2021-02-25 20:37 UTC, clarisse-lau commented on template.yaml
> +  ObjectReadAccounts:
updated the documentation

2021-02-25 20:44 UTC, zaro0508 commented on template.yaml
> +    Default: "id=d9df08ac799f2859d42a588b415111314cf66d0ffd072195f33b921db966b440,emailaddress=dagutman@gmail.com"
what if dagutman is no longer the `DSA`?  adding him as a default obscures this setting.  Would it not be better to not set a default but require the user who provisions the bucket to explicitly set one or more DSAs?

2021-02-25 20:57 UTC, clarisse-lau commented on template.yaml
> +    Default: "id=d9df08ac799f2859d42a588b415111314cf66d0ffd072195f33b921db966b440,emailaddress=dagutman@gmail.com"
This is granting the DSA AWS account read access though, not dave gutman himself as a user? 
But sure, I can separate them. I also have the canonical ID now and can use it instead, if that's better than email address?

2021-02-25 21:04 UTC, zaro0508 commented on template.yaml
> +    Default: "id=d9df08ac799f2859d42a588b415111314cf66d0ffd072195f33b921db966b440,emailaddress=dagutman@gmail.com"
ahh, ok. the email confused me, thought it was giving perms to dagutman specifically .  if your giving perms to an entire account and it's unlikely to change then i guess no problem keeping it as-is.

2021-02-25 21:11 UTC, clarisse-lau commented on template.yaml
> +    Default: "id=d9df08ac799f2859d42a588b415111314cf66d0ffd072195f33b921db966b440,emailaddress=dagutman@gmail.com"
yeah, it's for the account and unlikely to change
ok... thanks!

2021-02-26 00:44 UTC, merged