minerva image processing with batch
Sage-Bionetworks/s3-synapse-sync pull request #27
Opened 2021-03-11 00:07 UTC by clarisse-lau

Modify lambda to submit a batch job to run Minerva processing script when input image and visualization specification (json) files are added to bucket
- Update template for lambda
- Update lambda code
- Add docker files
- Update documentation

2021-03-11 00:24 UTC, milen-sage approved these changes
Very cool!

2021-03-19 21:49 UTC, zaro0508 requested changes

2021-03-19 21:49 UTC, zaro0508 commented on s3_synapse_sync/lambda_function.py
> +                print("{} image not found.".format(input_tiff))
not sure if this provides useful info.  would you have an `input_tiff` at all if you get 404?

2021-03-19 21:49 UTC, zaro0508 commented on s3_synapse_sync/lambda_function.py
> +        story_json = get_story_json(bucket,filename,prefix)
maybe name this var `story_json_files`?

2021-03-19 21:49 UTC, zaro0508 commented on s3_synapse_sync/lambda_function.py
> +        for json in story_json:
`for file in story_json_files`?

2021-03-19 21:49 UTC, zaro0508 commented on template.yaml
> +          Resource: "arn:aws:batch:*:*:*"
can we tighten this up to only allow submitting to the batch created in this template?

2021-03-19 21:49 UTC, zaro0508 commented on template.yaml
> +      ComputeEnvironmentName: !Join
this isn't required, can we let AWS manage the names?

2021-03-19 21:49 UTC, zaro0508 commented on template.yaml
> +        SecurityGroupIds:
you can remove the `SecurityGroup` input parameter and reference it with !ImportValue instead, like so..

```
SecurityGroupIds: [ !ImportValue {'Fn::Sub': '${AWS::Region}-computevpc-VpcDefaultSecurityGroup'} ]
```

2021-03-19 21:49 UTC, zaro0508 commented on template.yaml
> +      VpcId: !Ref VpcID
you can remove the `VpcID` input parameter and use this..

```
VpcId: [ !ImportValue {'Fn::Sub': '${AWS::Region}-computevpc-VPCId'} ]
```

2021-03-19 21:49 UTC, zaro0508 commented on template.yaml
> +      Tags:
you don't need this.  we pass in stack tags which will automatically tag all resources in here.

2021-03-19 21:49 UTC, zaro0508 commented on template.yaml
> +        Image: !Sub "${AWS::AccountId}.dkr.ecr.us-east-1.amazonaws.com/${DockerImage}"
you are assuming we are going to setup ECR in the same account?  i'm not we want to do that.  also this seems pretty restrictive, no?  can't the DockerImage come from multiple sources?  like an ECR from somewhere else or even dockerhub?

2021-03-19 21:49 UTC, zaro0508 commented on template.yaml
> +          CidrIp: !Ref CIDR
you can remove `CIDR` from the input parameters and reference it directly instead, like so..
```
CidrIp: [ !ImportValue {'Fn::Sub': '${AWS::Region}-computevpc-VpcCidr'} ]
```

2021-03-19 21:49 UTC, zaro0508 commented on template.yaml
> +        Subnets: !Ref Subnets
you can remove the Subnets input parameter and reference it with !ImportValue instead, like so..

```
Subnets: 
  - !ImportValue {'Fn::Sub': '${AWS::Region}-computevpc-PrivateSubnet'}
  - !ImportValue {'Fn::Sub': '${AWS::Region}-computevpc-PrivateSubnet1'}
  - !ImportValue {'Fn::Sub': '${AWS::Region}-computevpc-PrivateSubnet2'}
```

2021-03-19 21:49 UTC, zaro0508 commented on template.yaml
> +      LaunchTemplateName: !Join
this is not a required parameter, can we let AWS manage the name?

2021-03-19 21:49 UTC, zaro0508 commented on template.yaml
> +        BlockDeviceMappings:
wondering why you need a separate volume?  can't the docker just save stuff in `/tmp` folder?

2021-03-19 21:49 UTC, zaro0508 commented on template.yaml
> +      JobDefinitionName: !Join
this isn't a required parameter.  can we just let AWS manage names?

2021-03-19 21:49 UTC, zaro0508 commented on template.yaml
> +      JobQueueName: !Join
this isn't a required parameter, can we let AWS manage names?

2021-03-20 04:24 UTC, zaro0508 reviewed
Sorry i changed my mind about using `!ImportValue`. it was a bad idea, pass them in as parameters is a better approach.

2021-03-20 06:06 UTC, clarisse-lau commented on s3_synapse_sync/lambda_function.py
> +    if dirname == prefix and key.endswith('story.json'):
No, ‘story.json’ is the suffix we require, but submitted Minerva json files will have varying basenames e.g. <storyname>.story.json

2021-03-20 06:06 UTC, clarisse-lau commented on s3_synapse_sync/lambda_function.py
> +                print("{} image not found.".format(input_tiff))
I think this could still be useful, say if an incorrect (unpaired) image name is provided in the json ?

2021-03-20 06:06 UTC, clarisse-lau commented on s3_synapse_sync/lambda_function.py
> +    sync_to_synapse(bucket,event,eventname,filename,key)
They are not dependent, but If it’s alright to leave it as one function for now I will revisit this later

2021-03-20 06:06 UTC, clarisse-lau commented on template.yaml
> +        BlockDeviceMappings:
The images submitted will be up to 100GB, and when I tested with an 80GB file using /tmp there was not enough disk space

2021-03-20 06:07 UTC, clarisse-lau commented on template.yaml
> +    ConstraintDescription: >-
Updated to allow Docker images from multiple sources

2021-03-20 06:07 UTC, clarisse-lau commented on s3_synapse_sync/lambda_function.py
> +        story_json = get_story_json(bucket,filename,prefix)
Sure, updated.

2021-03-20 06:07 UTC, clarisse-lau commented on s3_synapse_sync/lambda_function.py
> +        for json in story_json:
Updated

2021-03-20 06:07 UTC, clarisse-lau commented on template.yaml
> +          Resource: "arn:aws:batch:*:*:*"
Updated

2021-03-20 06:07 UTC, clarisse-lau commented on template.yaml
> +      ComputeEnvironmentName: !Join
Removed name

2021-03-20 06:07 UTC, clarisse-lau commented on template.yaml
> +      Tags:
Removed tags

2021-03-20 06:08 UTC, clarisse-lau commented on template.yaml
> +      LaunchTemplateName: !Join
Removed name

2021-03-20 06:08 UTC, clarisse-lau commented on template.yaml
> +      JobDefinitionName: !Join
Removed

2021-03-20 06:08 UTC, clarisse-lau commented on template.yaml
> +      JobQueueName: !Join
Removed

2021-03-20 06:08 UTC, clarisse-lau commented on template.yaml
> +        Image: !Sub "${AWS::AccountId}.dkr.ecr.us-east-1.amazonaws.com/${DockerImage}"
Didn’t intend to make assumptions, just lack experience with batch and docker :)
Updated now to allow Docker images from multiple sources

2021-03-20 06:11 UTC, clarisse-lau commented
Ok, thanks Khai. 
Re: your question from slack- yes to the latter, I expect the command and entrypoint to be in the docker image

2021-03-22 16:12 UTC, zaro0508 requested changes

2021-03-23 02:40 UTC, clarisse-lau commented on s3_synapse_sync/lambda_function.py
> +    if dirname == prefix and key.endswith('story.json'):
it is in the docs ? https://github.com/Sage-Bionetworks/s3-synapse-sync/pull/27/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R233

2021-03-23 02:40 UTC, clarisse-lau commented on s3_synapse_sync/lambda_function.py
> +                print("{} image not found.".format(input_tiff))
also mentioned in the docs https://github.com/Sage-Bionetworks/s3-synapse-sync/pull/27/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R233

2021-03-23 02:40 UTC, clarisse-lau commented on template.yaml
> +  DockerImage:
Ok, will give this a go. So for step 2 I just need to update this line https://github.com/Sage-Bionetworks/scicomp-provisioner/blob/master/config/prod/s3-synapse-sync.yaml#L11 in the template to reference the new version (after I’ve tagged it)?

2021-03-23 02:48 UTC, clarisse-lau commented on README.md
> +4. Tag the build and push image to repository
Fixed. 
yeah, would otherwise be preferred?
and can you clarify for this step- will you be helping me build the docker image, or should I create a Docker Hub account and push the image to a registry there?

2021-03-23 02:49 UTC, clarisse-lau commented on template.yaml
> +        BlockDeviceMappings:
Ok, thanks Khai. For now I think I’ll also leave this as is, since I’ve tested increasing volume with a launch template and it works. After the initial round of Minerva story submissions, if we continue to use batch to render minerva images (which may not be the case as it sounds like there are other options in the works), I’ll revisit this and make improvements 
Have also added an AMI parameter. I think if not specified the default amazon linux AMI is used

2021-03-29 16:00 UTC, zaro0508 requested changes

2021-03-29 16:11 UTC, milen-sage commented on template.yaml
> +    Default: /aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id
hi @zaro0508 , Clarisse (and she can correct me if I am wrong) has tested this code on ISB's S3. We have a deadline this week and as she mentioned above this is only a first iteration of this processing workflow. Could we proceed w/ merging this unless you see critical issues, so that we can test it in Sage's infra? If there are critical issues (i.e. security or access problems) could you focus the review on that? We need to open submission of images and Minerva stories Apr 5, and we definitely want to use the next few days to test beforehand. This has been open for 19 days; cc-in @jaeddy so that he's aware of the status here as well.

2021-03-29 16:31 UTC, clarisse-lau commented on template.yaml
> +    Default: /aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id
@zaro0508 this will reference the latest amazon linux 2 image ID (https://docs.aws.amazon.com/AmazonECS/latest/developerguide/retrieve-ecs-optimized_AMI.html#ecs-optimized-ami-parameter-examples-5 
https://us-east-1.console.aws.amazon.com/systems-manager/parameters/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id/description?region=us-east-1#), but again this is my first time working with batch, so if you would recommend I do things differently (use a specific image ID or don't specify a default?), I'm happy to change (though taking Milen's comment into account, perhaps non-critical improvements can be made at a later time? and yes, I did test creation of this stack and the processing code on ISB's AWS account)

2021-03-29 18:27 UTC, zaro0508 commented on template.yaml
> +    Default: /aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id
@clarisse-lau  ahh, ok.  didn't know that AWS has this special reference.  looks good then.

@milen-sage not sure what to tell you,  these things take time, especially with the async communication of doing it thru github PRs.   I have other projects to work on and review and it's IT's responsibility to understand what gets deployed to a production account and the ramifications it presents.  What I will say is that if you want this to be a speedier process you should try using one of our synchronous communications channels like slack or VOIP.

2021-03-30 19:55 UTC, zaro0508 approved these changes

2021-03-30 21:22 UTC, clarisse-lau commented on template.yaml
> +  DockerImage:
@zaro0508 thanks, will do steps 4 & 5 next. 
would you be able to help me with step 6? or what should I put for the `Subnets`, and `VpcID` parameters since I'm not using !ImportValue here. and the `DockerImage` parameter? (I created a Docker Hub account to test with, but should the image be pushed to a Sage registry instead?)

2021-04-02 16:31 UTC, zaro0508 approved these changes

2021-04-02 20:23 UTC, merged