change version referenced in template
Sage-Bionetworks/s3-synapse-sync pull request #32
Opened 2021-03-29 15:49 UTC by clarisse-lau

2021-03-29 18:31 UTC, zaro0508 requested changes

2021-03-29 18:31 UTC, zaro0508 commented on template.yaml
> +    SemanticVersion: "1.1"
if you set this to 1.1. then you will need to redo your `v1.1` tag since you've already created a `v1.1` tag.  do you plan to do that?

an alternative is to set to `1.2` then create a new `v1.2` tag

2021-03-29 18:53 UTC, clarisse-lau commented on template.yaml
> +    SemanticVersion: "1.1"
ah ok. have changed to 1.2 and will create a v1.2 tag now

2021-03-29 19:08 UTC, clarisse-lau commented on template.yaml
> +    SemanticVersion: "1.1"
ok, done. and updated the PR in scicomp-provisioner to pin v1.2 https://github.com/Sage-Bionetworks/scicomp-provisioner/pull/440

2021-03-29 21:40 UTC, zaro0508 requested changes

2021-03-29 21:40 UTC, zaro0508 commented on template.yaml
>      SourceCodeUrl: "https://github.com/Sage-Bionetworks-IT/s3-synapse-sync/tree/0.0.1"
please update version here as well.

2021-03-29 21:40 UTC, zaro0508 commented on template.yaml
> +    SemanticVersion: "1.2"
i see you've already released `v1.2` without this change.  so that tag will contain `v1.1` not `v1.2`.  What you want to do is fix this merge before creating your tag.  

so now you have 2 options, fix up your `v1.2` tag or merge this THEN create `v1.3` tag.

2021-03-29 22:23 UTC, clarisse-lau commented on template.yaml
> +    SemanticVersion: "1.2"
ok sorry, I think I (finally) get it ... so to clarify, the order should be as such? :
1. merge this as is
2. create a `v1.3` tag
3. update the [scicomp-provisioner PR](https://github.com/Sage-Bionetworks/scicomp-provisioner/pull/440) to pin `v1.3`

2021-03-29 22:23 UTC, clarisse-lau commented on template.yaml
>      SourceCodeUrl: "https://github.com/Sage-Bionetworks-IT/s3-synapse-sync/tree/0.0.1"
should the repo just be `Sage-Bionetworks`?

2021-03-29 22:45 UTC, zaro0508 commented on template.yaml
>      SourceCodeUrl: "https://github.com/Sage-Bionetworks-IT/s3-synapse-sync/tree/0.0.1"
yes, you are correct.

2021-03-29 22:46 UTC, zaro0508 commented on template.yaml
> +    SemanticVersion: "1.2"
step 2 and 3 are correct.  for step 1 you want  to set version in this template to `1.3`.  basically your tag/release version needs to match the version in this template.

2021-03-29 23:21 UTC, clarisse-lau commented on template.yaml
>      SourceCodeUrl: "https://github.com/Sage-Bionetworks-IT/s3-synapse-sync/tree/0.0.1"
updated version and repository name

2021-03-29 23:22 UTC, clarisse-lau commented on template.yaml
> +    SemanticVersion: "1.2"
ok, thanks for walking me through this. look ok now for step 1?

2021-03-30 00:33 UTC, zaro0508 approved these changes

2021-03-30 14:51 UTC, merged